MEMORY
{
  ROM : ORIGIN = 0x80000000, LENGTH = 2K
  SRAM : ORIGIN = 0x00000000, LENGTH = 16K
}

REGION_ALIAS("REGION_TEXT", ROM);
REGION_ALIAS("REGION_RODATA", ROM);
REGION_ALIAS("REGION_DATA", SRAM);
REGION_ALIAS("REGION_BSS", SRAM);
REGION_ALIAS("REGION_HEAP", SRAM);
REGION_ALIAS("REGION_STACK", SRAM);
