[package]
name = "blink"
version = "0.1.0"
edition.workspace = true

[dependencies]
panic-halt.workspace = true
riscv.workspace = true
riscv-rt.workspace = true
volatile-register.workspace = true

[[bin]]
name = "blink"
path = "sw/main.rs"
test = false
doctest = false
bench = false
