name = "ae350_uart"
version = 5

[device]
family = "GW5AST-138B"
part = "GW5AST-LV138FPG676AC1/I0"

[hdl]
standard = "sysv2017"
top = "top"

[files]
verilog = [
  "hw/**/*.sv",
  "hw/**/*[!_tmp].v",
  "../rtl/**/*.sv"
]
cst = "phy.cst"
# sdc = "timings.sdc"

[pnr]
place_option = 3
route_option = 1
replicate = true

[bitstream]
compress = true

[programmer]
fs = "impl/pnr/project.fs"

preset.sram = { op = "2" }
preset.spi = { op = "53" }
